[package]
name = "ducking-compressor"
description = "Skuiz example: rudimentary sidechain ducking compressor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
skuiz-core.workspace = true
skuiz-clap.workspace = true
