//! trigger-note: C DSP over plain FFI, driving generated MIDI.
//!
//! An envelope follower written in quick-and-dirty C watches the input; when
//! the signal crosses the threshold the plugin emits a MIDI note, and when
//! it falls away again the note is released. It demonstrates three things at
//! once: C DSP over plain FFI (no wrapper layer — see
//! `build.rs` and `envelope.c`), MIDI generated by that DSP and distributed
//! by the plugin interface layer, and configuration dropdowns that are just
//! choice parameters.

use skuiz_core::{MidiOut, ParamDef, PluginInfo, Processor};

const P_THRESHOLD: u32 = 0;
const P_NOTE: u32 = 1;
const P_CHANNEL: u32 = 2;
const P_VELOCITY: u32 = 3;

/// Mirrors `skuiz_env` in envelope.h. Plain data, so C owns the layout and
/// Rust just hands over a pointer.
#[repr(C)]
#[derive(Default)]
struct CEnv {
    env: f32,
    attack: f32,
    release: f32,
    open: i32,
}

extern "C" {
    fn skuiz_env_init(e: *mut CEnv, sample_rate: f32);
    fn skuiz_env_scan(
        e: *mut CEnv,
        samples: *const f32,
        frames: i32,
        threshold: f32,
        out_closed: *mut i32,
    ) -> i32;
}

/// Note names for the dropdown, one octave; the parameter value is the
/// offset from C3 (MIDI 60).
const NOTE_NAMES: &[&str] = &[
    "C3", "C#3", "D3", "D#3", "E3", "F3", "F#3", "G3", "G#3", "A3", "A#3", "B3",
];
const BASE_NOTE: u8 = 60;

pub struct TriggerNote {
    env: CEnv,
    threshold: f64,
    note_choice: f64,
    channel: f64,
    velocity: f64,
    /// The note currently sounding, so the right one gets released even if
    /// the note or channel dropdown moved while it was held.
    sounding: Option<(u8, u8)>,
}

impl Default for TriggerNote {
    fn default() -> Self {
        Self {
            env: CEnv::default(),
            threshold: 0.1,
            note_choice: 0.0,
            channel: 0.0,
            velocity: 100.0,
            sounding: None,
        }
    }
}

impl TriggerNote {
    fn note(&self) -> u8 {
        BASE_NOTE + self.note_choice.round().clamp(0.0, 11.0) as u8
    }
}

impl Processor for TriggerNote {
    fn info() -> PluginInfo {
        PluginInfo {
            id: "org.skuiz.trigger-note",
            name: "Trigger Note",
            vendor: "Skuiz",
            version: env!("CARGO_PKG_VERSION"),
            description: "C envelope follower that fires MIDI notes",
        }
    }

    fn params() -> &'static [ParamDef] {
        // A named const, not a bare `&[...]`: the array calls a const fn
        // (`channel_param`), which blocks const-promotion of a temporary.
        const PARAMS: &[ParamDef] = &[
            ParamDef {
                id: P_THRESHOLD,
                name: "Threshold",
                min: 0.0,
                max: 1.0,
                default: 0.1,
                choices: &[],
                shared: true,
            },
            // Choice params render as dropdowns in hosts and in our editor.
            ParamDef {
                id: P_NOTE,
                name: "Note",
                min: 0.0,
                max: 0.0,
                default: 0.0,
                choices: NOTE_NAMES,
                shared: true,
            },
            skuiz_midi::channel_param(P_CHANNEL),
            ParamDef {
                id: P_VELOCITY,
                name: "Velocity",
                min: 1.0,
                max: 127.0,
                default: 100.0,
                choices: &[],
                shared: true,
            },
        ];
        PARAMS
    }

    fn emits_midi() -> bool {
        true
    }

    fn activate(&mut self, sample_rate: f64, _max_frames: u32) {
        unsafe { skuiz_env_init(&mut self.env, sample_rate as f32) };
        self.sounding = None;
    }

    fn set_param(&mut self, id: u32, value: f64) {
        match id {
            P_THRESHOLD => self.threshold = value.clamp(0.0, 1.0),
            P_NOTE => self.note_choice = value.round().clamp(0.0, 11.0),
            P_CHANNEL => self.channel = value.round().clamp(0.0, 15.0),
            P_VELOCITY => self.velocity = value.round().clamp(1.0, 127.0),
            _ => {}
        }
    }

    fn get_param(&self, id: u32) -> f64 {
        match id {
            P_THRESHOLD => self.threshold,
            P_NOTE => self.note_choice,
            P_CHANNEL => self.channel,
            P_VELOCITY => self.velocity,
            _ => 0.0,
        }
    }

    fn process(&mut self, channels: &mut [&mut [f32]], midi: &mut MidiOut) {
        let Some(input) = channels.first() else {
            return;
        };
        if input.is_empty() {
            return;
        }

        let mut closed = 0i32;
        let crossing = unsafe {
            skuiz_env_scan(
                &mut self.env,
                input.as_ptr(),
                input.len() as i32,
                self.threshold as f32,
                &mut closed,
            )
        };

        // Release first: a gate that closed and reopened in the same block
        // must produce note-off then note-on, not the reverse. Note-off is
        // block-quantized (pushed at frame 0) — only note-on is sample-accurate.
        if closed != 0 {
            if let Some((ch, key)) = self.sounding.take() {
                midi.push(0, skuiz_midi::note_off(ch, key, 0));
            }
        }
        if crossing >= 0 {
            let ch = skuiz_midi::channel_of(self.channel);
            let key = self.note();
            // No retrigger guard needed: the gate can't reopen while open, so
            // any sounding note was already released by the `closed` branch.
            midi.push(
                crossing as u32,
                skuiz_midi::note_on(ch, key, self.velocity as u8),
            );
            self.sounding = Some((ch, key));
        }
    }

    fn editor_html() -> Option<&'static str> {
        Some(include_str!("editor.html"))
    }

    fn editor_size() -> (u32, u32) {
        (340, 210)
    }
}

skuiz_clap::export_clap!(TriggerNote);
